execute if entity @a[scores={D_map_random=0}] run function st:deathmatch/clone/countryside
execute if entity @a[scores={D_map_random=1}] run function st:deathmatch/clone/nether_arena
execute if entity @a[scores={D_map_random=2}] run function st:deathmatch/clone/office
execute if entity @a[scores={D_map_random=3}] run function st:deathmatch/clone/space_x
execute if entity @a[scores={D_map_random=4}] run function st:deathmatch/clone/bridge
execute if entity @a[scores={D_map_random=5}] run function st:deathmatch/clone/trench_original
execute if entity @a[scores={D_map_random=6}] run function st:deathmatch/clone/desert_city
execute if entity @a[scores={D_map_random=7}] run function st:deathmatch/clone/desert_fortress
execute if entity @a[scores={D_map_random=8}] run function st:deathmatch/clone/castle
execute if entity @a[scores={D_map_random=9}] run function st:deathmatch/clone/neo_harbor
execute if entity @a[scores={D_map_random=10}] run function st:deathmatch/clone/old_harbor
execute if entity @a[scores={D_map_random=11}] run function st:deathmatch/clone/old_hotel
execute if entity @a[scores={D_map_random=12}] run function st:deathmatch/clone/ancient_temple
execute if entity @a[scores={D_map_random=13}] run function st:deathmatch/clone/prison
execute if entity @a[scores={D_map_random=14}] run function st:deathmatch/clone/sky_castle
execute if entity @a[scores={D_map_random=15}] run function st:deathmatch/clone/nether_fortress
execute if entity @a[scores={D_map_random=16}] run function st:deathmatch/clone/rage_of_god
execute if entity @a[scores={D_map_random=17}] run function st:deathmatch/clone/maze_01
execute if entity @a[scores={D_map_random=18}] run function st:deathmatch/clone/bunker
execute if entity @a[scores={D_map_random=19}] run function st:deathmatch/clone/old_museum
execute if entity @a[scores={D_map_random=20}] run function st:deathmatch/clone/midden
execute if entity @a[scores={D_map_random=21}] run function st:deathmatch/clone/mine
execute if entity @a[scores={D_map_random=22}] run function st:deathmatch/clone/ancient_portal
execute if entity @a[scores={D_map_random=23}] run function st:deathmatch/clone/snowy_outpost
execute if entity @a[scores={D_map_random=24}] run function st:deathmatch/clone/neo_school
execute if entity @a[scores={D_map_random=25}] run function st:deathmatch/clone/nether_castle
execute if entity @a[scores={D_map_random=26}] run function st:deathmatch/clone/farmland_original
execute if entity @a[scores={D_map_random=27}] run function st:deathmatch/clone/farmland_trench
execute if entity @a[scores={D_map_random=28}] run function st:deathmatch/clone/datacenter
execute if entity @a[scores={D_map_random=29}] run function st:deathmatch/clone/old_metro
execute if entity @a[scores={D_map_random=30}] run function st:deathmatch/clone/stone_arena
execute if entity @a[scores={D_map_random=31}] run function st:deathmatch/clone/neo_resort
execute if entity @a[scores={D_map_random=32}] run function st:deathmatch/clone/old_resort
execute if entity @a[scores={D_map_random=33}] run function st:deathmatch/clone/portal_maze
execute if entity @a[scores={D_map_random=34}] run function st:deathmatch/clone/old_park
execute if entity @a[scores={D_map_random=35}] run function st:deathmatch/clone/oasis_village
execute if entity @a[scores={D_map_random=36}] run function st:deathmatch/clone/freight_warehouse
execute if entity @a[scores={D_map_random=37}] run function st:deathmatch/clone/jungle_temple
execute if entity @a[scores={D_map_random=38}] run function st:deathmatch/clone/maze_small
execute if entity @a[scores={D_map_random=39}] run function st:deathmatch/clone/maze_huge